### ISSUE TITLE
Ansible Galaxy - Error installing multiple roles from requirements.yml

### ISSUE THREAD

**Issue by shishir-intelli** [apigee/devportal-kickstart-drupal-ansible-installer#12]
## Description
Running - **$ ansible-galaxy install -r requirements.yml** 
from root of the project throwing 

_**[WARNING]: - roles was NOT installed successfully: Content has no field named 'owner'**_

Due to missing roles I am facing "_the role 'geerlingguy.mysql' was not found_" error while executing 
$ ansible-playbook playbook.yml

## Steps to Reproduce
1. Go to '[https://github.com/apigee/devportal-kickstart-drupal-ansible-installer#apigee-devportal-kickstart-for-drupal-ansible-installation-scripts](https://github.com/apigee/devportal-kickstart-drupal-ansible-installer#apigee-devportal-kickstart-for-drupal-ansible-installation-scripts)' and follow installation steps.
2. After cloning repo and installing Ansible.
3. Run  **$ ansible-galaxy install -r requirements.yml**

## Actual Behavior
$ ansible-galaxy install -r requirements.yml
- downloading role 'roles', owned by
 **[WARNING]: - roles was NOT installed successfully: Content has no field named 'owner'**

## Expected Behavior
$ ansible-galaxy install -r requirements.yml
-downloading role 'php', owned by geerlingguy
- geerlingguy.php (###) was installed successfully

## Screenshots
![cygwin](https://user-images.githubusercontent.com/75600200/102259296-f0754a80-3f34-11eb-8a9c-e40dd8602023.png)

##Note
I am working on windows machine and using Cygwin64 Terminal for installing Apigee Kickstart developer portal for Drupal using Ansible.

**Comment by divya-intelli** [comment]
A workaround to resolve the error when running 'ansible-galaxy install -r requirements.yml'  is to individually install all the roles that are mentioned in requirement.yml file. 
eg :  ansible-galaxy install geerlingguy.php

![galaxyphp](https://user-images.githubusercontent.com/75604843/102326751-cf4f4100-3faa-11eb-960d-7f5107525ef6.png)

**Comment by cnovak** [comment]
I followed instructions and did not get any errors, are you running a old version of ansible? The [collection subcomand only exists in ansible 2.9+](https://github.com/ansible/galaxy/issues/2037#issuecomment-537237801).


```
% ansible-galaxy --version                                                                                                                                                (master)devportal-kickstart-drupal-ansible-installer
ansible-galaxy 2.10.3
 % ansible-galaxy install -r requirements.yml                                                                                                                              (master)devportal-kickstart-drupal-ansible-installer
Starting galaxy role install process
- downloading role 'php', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/4.2.0.tar.gz
- extracting geerlingguy.php to /Users/chrisnovak/Downloads/devportal-kickstart-drupal-ansible-installer/roles/geerlingguy.php
- geerlingguy.php (4.2.0) was installed successfully
- downloading role 'nginx', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-nginx/archive/2.7.0.tar.gz
- extracting geerlingguy.nginx to /Users/chrisnovak/Downloads/devportal-kickstart-drupal-ansible-installer/roles/geerlingguy.nginx
- geerlingguy.nginx (2.7.0) was installed successfully
- downloading role 'repo-remi', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-repo-remi/archive/1.2.0.tar.gz
- extracting geerlingguy.repo-remi to /Users/chrisnovak/Downloads/devportal-kickstart-drupal-ansible-installer/roles/geerlingguy.repo-remi
- geerlingguy.repo-remi (1.2.0) was installed successfully
- downloading role 'repo-epel', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-repo-epel/archive/1.3.0.tar.gz
- extracting geerlingguy.repo-epel to /Users/chrisnovak/Downloads/devportal-kickstart-drupal-ansible-installer/roles/geerlingguy.repo-epel
- geerlingguy.repo-epel (1.3.0) was installed successfully
- downloading role 'drupal', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-drupal/archive/3.0.1.tar.gz
- extracting geerlingguy.drupal to /Users/chrisnovak/Downloads/devportal-kickstart-drupal-ansible-installer/roles/geerlingguy.drupal
- geerlingguy.drupal (3.0.1) was installed successfully
- downloading role 'mysql', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-mysql/archive/3.1.0.tar.gz
- extracting geerlingguy.mysql to /Users/chrisnovak/Downloads/devportal-kickstart-drupal-ansible-installer/roles/geerlingguy.mysql
- geerlingguy.mysql (3.1.0) was installed successfully
- downloading role 'composer', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-composer/archive/1.7.6.tar.gz
- extracting geerlingguy.composer to /Users/chrisnovak/Downloads/devportal-kickstart-drupal-ansible-installer/roles/geerlingguy.composer
- geerlingguy.composer (1.7.6) was installed successfully
- downloading role 'git', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-git/archive/3.0.0.tar.gz
- extracting geerlingguy.git to /Users/chrisnovak/Downloads/devportal-kickstart-drupal-ansible-installer/roles/geerlingguy.git
- geerlingguy.git (3.0.0) was installed successfully

```

**Comment by cnovak** [comment]
@shishir-intelli I will close this issue, please reopen if this did not solve your problem.
