### ISSUE TITLE
php5.4 getting installed

### ISSUE THREAD

**Issue by jackd12** [apigee/devportal-kickstart-drupal-ansible-installer#8]
Hi, i tried to run this playbook but it keep checking (or installs) php 5.4 while i already have php 7.3 installed on my system and because of that the composer step fails saying php 5.4 is not a valid version. (- drupal/apigee_m10n 1.0.0-beta3 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.)

Is there a way to check for a diff version ?

**Comment by giteshk** [comment]
Can you paste the log here.

I have seen with some OS the php libraries default to use the 5.* version even when they have php7.3 installed. I have seen that problem with bc-math php library in the past.

Please ensure you have the right packages installed.  You can use this to install the right packages for your OS : 
https://www.drupal.org/docs/contributed-modules/apigee-developer-portal-kickstart/use-kickstart-with-apigee-edge-for#s-install-php-73

**Comment by jackd12** [comment]
Hey Gitesh, thanks for quick reply .. so i installed php 7.3 before running the playbook but it seems to still go check for php and then installs php 5.4. I am wondering if this check is checking the wrong dir. Here's what my php version and out put is 

php -version
PHP 7.3.11 (cli) (built: Oct 31 2019 08:30:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11, Copyright (c) 1999-2018, by Zend Technologies

# which php
/bin/php

============================

Now when i run the installer , the expectation is that php is alreadyy installed, playbook should recognize that and move on but that doesn't seem to happen, not sure if i am doing something wrong here ... 

ansible-playbook playbook.yml

PLAY [dbservers] *******************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : include_tasks] *******************************************************************************************************************************************
included: /apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.mysql/tasks/variables.yml for db1

TASK [geerlingguy.mysql : Include OS-specific variables.] **************************************************************************************************************************
ok: [db1] => (item=/apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.mysql/vars/RedHat-7.yml)

TASK [geerlingguy.mysql : Define mysql_packages.] **********************************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : Define mysql_daemon.] ************************************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : Define mysql_slow_query_log_file.] ***********************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : Define mysql_log_error.] *********************************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : Define mysql_syslog_tag.] ********************************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : Define mysql_pid_file.] **********************************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : Define mysql_config_file.] *******************************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : Define mysql_config_include_dir.] ************************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : Define mysql_socket.] ************************************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : Define mysql_supports_innodb_large_prefix.] **************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : include_tasks] *******************************************************************************************************************************************
included: /apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.mysql/tasks/setup-RedHat.yml for db1

TASK [geerlingguy.mysql : Ensure MySQL packages are installed.] ********************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : include_tasks] *******************************************************************************************************************************************
skipping: [db1]

TASK [geerlingguy.mysql : include_tasks] *******************************************************************************************************************************************
skipping: [db1]

TASK [geerlingguy.mysql : Check if MySQL packages were installed.] *****************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : include_tasks] *******************************************************************************************************************************************
included: /apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.mysql/tasks/configure.yml for db1

TASK [geerlingguy.mysql : Get MySQL version.] **************************************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : Copy my.cnf global MySQL configuration.] *****************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : Verify mysql include directory exists.] ******************************************************************************************************************
skipping: [db1]

TASK [geerlingguy.mysql : Copy my.cnf override files into include directory.] ******************************************************************************************************

TASK [geerlingguy.mysql : Create slow query log file (if configured).] *************************************************************************************************************
skipping: [db1]

TASK [geerlingguy.mysql : Create datadir if it does not exist] *********************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : Set ownership on slow query log file (if configured).] ***************************************************************************************************
skipping: [db1]

TASK [geerlingguy.mysql : Create error log file (if configured).] ******************************************************************************************************************
skipping: [db1]

TASK [geerlingguy.mysql : Set ownership on error log file (if configured).] ********************************************************************************************************
skipping: [db1]

TASK [geerlingguy.mysql : Ensure MySQL is started and enabled on boot.] ************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : include_tasks] *******************************************************************************************************************************************
included: /apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.mysql/tasks/secure-installation.yml for db1

TASK [geerlingguy.mysql : Ensure default user is present.] *************************************************************************************************************************
skipping: [db1]

TASK [geerlingguy.mysql : Copy user-my.cnf file with password credentials.] ********************************************************************************************************
skipping: [db1]

TASK [geerlingguy.mysql : Disallow root login remotely] ****************************************************************************************************************************
ok: [db1] => (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1'))

TASK [geerlingguy.mysql : Get list of hosts for the root user.] ********************************************************************************************************************
skipping: [db1]

TASK [geerlingguy.mysql : Update MySQL root password for localhost root account (5.7.x).] ******************************************************************************************

TASK [geerlingguy.mysql : Update MySQL root password for localhost root account (< 5.7.x).] ****************************************************************************************

TASK [geerlingguy.mysql : Copy .my.cnf file with root password credentials.] *******************************************************************************************************
skipping: [db1]

TASK [geerlingguy.mysql : Get list of hosts for the anonymous user.] ***************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : Remove anonymous MySQL users.] ***************************************************************************************************************************

TASK [geerlingguy.mysql : Remove MySQL test database.] *****************************************************************************************************************************
ok: [db1]

TASK [geerlingguy.mysql : include_tasks] *******************************************************************************************************************************************
included: /apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.mysql/tasks/databases.yml for db1

TASK [geerlingguy.mysql : Ensure MySQL databases are present.] *********************************************************************************************************************
ok: [db1] => (item={u'collation': u'latin1_general_ci', u'name': u'devportal', u'encoding': u'latin1'})

TASK [geerlingguy.mysql : include_tasks] *******************************************************************************************************************************************
included: /apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.mysql/tasks/users.yml for db1

TASK [geerlingguy.mysql : Ensure MySQL users are present.] *************************************************************************************************************************
aok: [db1] => (item=None)
ok: [db1]

TASK [geerlingguy.mysql : include_tasks] *******************************************************************************************************************************************
included: /apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.mysql/tasks/replication.yml for db1

TASK [geerlingguy.mysql : Ensure replication user exists on master.] ***************************************************************************************************************
skipping: [db1]

TASK [geerlingguy.mysql : Check slave replication status.] *************************************************************************************************************************
skipping: [db1]

TASK [geerlingguy.mysql : Check master replication status.] ************************************************************************************************************************
skipping: [db1]

TASK [geerlingguy.mysql : Configure replication on the slave.] *********************************************************************************************************************
skipping: [db1]

TASK [geerlingguy.mysql : Start replication.] **************************************************************************************************************************************
skipping: [db1]

PLAY [webservers] ******************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.nginx : Include OS-specific variables.] **************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.nginx : Define nginx_user.] **************************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.nginx : include_tasks] *******************************************************************************************************************************************
included: /apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.nginx/tasks/setup-RedHat.yml for web1

TASK [geerlingguy.nginx : Enable nginx repo.] **************************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.nginx : Ensure nginx is installed.] ******************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.nginx : include_tasks] *******************************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.nginx : include_tasks] *******************************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.nginx : include_tasks] *******************************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.nginx : include_tasks] *******************************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.nginx : include_tasks] *******************************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.nginx : Remove default nginx vhost config file (if configured).] *************************************************************************************************
skipping: [web1]

TASK [geerlingguy.nginx : Ensure nginx_vhost_path exists.] *************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.nginx : Add managed vhost config files.] *************************************************************************************************************************

TASK [geerlingguy.nginx : Remove managed vhost config files.] **********************************************************************************************************************

TASK [geerlingguy.nginx : Remove legacy vhosts.conf file.] *************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.nginx : Copy nginx configuration in place.] **********************************************************************************************************************
ok: [web1]

TASK [geerlingguy.nginx : Ensure nginx service is running as configured.] **********************************************************************************************************
ok: [web1]

TASK [geerlingguy.php : Include OS-specific variables.] ****************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.php : Define php_packages.] **************************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.php : Define php_webserver_daemon.] ******************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.php : Define php_conf_paths.] ************************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.php : Define php_extension_conf_paths.] **************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.php : Define php_apc_conf_filename.] *****************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.php : Define php_opcache_conf_filename (Ubuntu 16.04).] **********************************************************************************************************
skipping: [web1]

TASK [geerlingguy.php : Define php_opcache_conf_filename.] *************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.php : Define php_fpm_conf_path.] *********************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.php : include_tasks] *********************************************************************************************************************************************
included: /apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.php/tasks/setup-RedHat.yml for web1

TASK [geerlingguy.php : Ensure PHP packages are installed.] ************************************************************************************************************************
changed: [web1]

TASK [geerlingguy.php : include_tasks] *********************************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.php : include_tasks] *********************************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.php : include_tasks] *********************************************************************************************************************************************
included: /apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.php/tasks/configure.yml for web1

TASK [geerlingguy.php : Ensure configuration directories exist.] *******************************************************************************************************************
ok: [web1] => (item=/etc)
ok: [web1] => (item=/etc/php.d)

TASK [geerlingguy.php : Place PHP configuration file in place.] ********************************************************************************************************************
changed: [web1] => (item=/etc)

TASK [geerlingguy.php : include_tasks] *********************************************************************************************************************************************
included: /apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.php/tasks/configure-apcu.yml for web1

TASK [geerlingguy.php : Check for existing APCu config files.] *********************************************************************************************************************
ok: [web1] => (item=/etc/php.d)

TASK [geerlingguy.php : Remove any non-role-supplied APCu config files.] ***********************************************************************************************************
changed: [web1] => (item=[{u'ansible_loop_var': u'item', u'item': u'/etc/php.d', u'changed': False, u'failed': False, u'examined': 31, u'msg': u'', u'invocation': {u'module_args': {u'excludes': None, u'paths': [u'/etc/php.d'], u'file_type': u'file', u'age': None, u'contains': u'extension(\\s+)?=(\\s+)?apc[u]?\\.so', u'recurse': False, u'age_stamp': u'mtime', u'patterns': [u'*'], u'depth': None, u'get_checksum': False, u'use_regex': False, u'follow': False, u'hidden': False, u'size': None}}, u'matched': 2}, {u'islnk': False, u'uid': 0, u'rgrp': True, u'xoth': False, u'rusr': True, u'woth': False, u'nlink': 1, u'issock': False, u'mtime': 1461157351.0, u'gr_name': u'root', u'path': u'/etc/php.d/apcu.ini', u'xusr': False, u'atime': 1600879292.5997243, u'inode': 4230945, u'isgid': False, u'size': 2435, u'isdir': False, u'ctime': 1600879292.5627208, u'roth': True, u'wgrp': False, u'xgrp': False, u'isuid': False, u'dev': 64768, u'isblk': False, u'isreg': True, u'isfifo': False, u'mode': u'0644', u'pw_name': u'root', u'gid': 0, u'ischr': False, u'wusr': True}])
skipping: [web1] => (item=[{u'ansible_loop_var': u'item', u'item': u'/etc/php.d', u'changed': False, u'failed': False, u'examined': 31, u'msg': u'', u'invocation': {u'module_args': {u'excludes': None, u'paths': [u'/etc/php.d'], u'file_type': u'file', u'age': None, u'contains': u'extension(\\s+)?=(\\s+)?apc[u]?\\.so', u'recurse': False, u'age_stamp': u'mtime', u'patterns': [u'*'], u'depth': None, u'get_checksum': False, u'use_regex': False, u'follow': False, u'hidden': False, u'size': None}}, u'matched': 2}, {u'islnk': False, u'uid': 0, u'rgrp': True, u'xoth': False, u'rusr': True, u'woth': False, u'nlink': 1, u'issock': False, u'mtime': 1600811604.7835424, u'gr_name': u'root', u'path': u'/etc/php.d/50-apc.ini', u'xusr': False, u'atime': 1600811605.4486065, u'inode': 6291761, u'isgid': False, u'size': 66, u'isdir': False, u'ctime': 1600811604.9915624, u'roth': True, u'wgrp': False, u'xgrp': False, u'isuid': False, u'dev': 64768, u'isblk': False, u'isreg': True, u'isfifo': False, u'mode': u'0644', u'pw_name': u'root', u'gid': 0, u'ischr': False, u'wusr': True}])

TASK [geerlingguy.php : Ensure APCu config file is present.] ***********************************************************************************************************************
ok: [web1] => (item=/etc/php.d)

TASK [geerlingguy.php : Remove APCu config file if APC is disabled.] ***************************************************************************************************************
skipping: [web1] => (item=/etc/php.d)

TASK [geerlingguy.php : include_tasks] *********************************************************************************************************************************************
included: /apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.php/tasks/configure-opcache.yml for web1

TASK [geerlingguy.php : Check for existing OpCache config files.] ******************************************************************************************************************
ok: [web1] => (item=/etc/php.d)

TASK [geerlingguy.php : Remove any non-role-supplied OpCache config files.] ********************************************************************************************************
skipping: [web1] => (item=[{u'ansible_loop_var': u'item', u'item': u'/etc/php.d', u'changed': False, u'failed': False, u'examined': 30, u'msg': u'', u'invocation': {u'module_args': {u'excludes': None, u'paths': [u'/etc/php.d'], u'file_type': u'file', u'age': None, u'contains': u'zend_extension(\\s+)?=(\\s+)?opcache\\.so', u'recurse': False, u'age_stamp': u'mtime', u'patterns': [u'*'], u'depth': None, u'get_checksum': False, u'use_regex': False, u'follow': False, u'hidden': False, u'size': None}}, u'matched': 1}, {u'islnk': False, u'uid': 0, u'rgrp': True, u'xoth': False, u'rusr': True, u'woth': False, u'nlink': 1, u'issock': False, u'mtime': 1600811605.8826485, u'gr_name': u'root', u'path': u'/etc/php.d/10-opcache.ini', u'xusr': False, u'atime': 1600811610.1640613, u'inode': 4230957, u'isgid': False, u'size': 302, u'isdir': False, u'ctime': 1600811606.095669, u'roth': True, u'wgrp': False, u'xgrp': False, u'isuid': False, u'dev': 64768, u'isblk': False, u'isreg': True, u'isfifo': False, u'mode': u'0644', u'pw_name': u'root', u'gid': 0, u'ischr': False, u'wusr': True}])

TASK [geerlingguy.php : Ensure OpCache config file is present.] ********************************************************************************************************************
ok: [web1] => (item=/etc/php.d)

TASK [geerlingguy.php : Remove OpCache config file if OpCache is disabled.] ********************************************************************************************************
skipping: [web1] => (item=/etc/php.d)

TASK [geerlingguy.php : include_tasks] *********************************************************************************************************************************************
included: /apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.php/tasks/configure-fpm.yml for web1

TASK [geerlingguy.php : Define php_fpm_daemon.] ************************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.php : Define php_fpm_pool_conf_path.] ****************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.php : Define php_fpm_pool_user.] *********************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.php : Define php_fpm_pool_group.] ********************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.php : Stat php_fpm_pool_conf_path] *******************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.php : Ensure the default pool directory exists.] *****************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.php : Ensure the default pool exists.] ***************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.php : Configure php-fpm pool (if enabled).] **********************************************************************************************************************
changed: [web1] => (item={u'regexp': u'^user.?=.+$', u'line': u'user = nginx'})
changed: [web1] => (item={u'regexp': u'^group.?=.+$', u'line': u'group = nginx'})
ok: [web1] => (item={u'regexp': u'^listen.?=.+$', u'line': u'listen = 127.0.0.1:9000'})
ok: [web1] => (item={u'regexp': u'^listen\\.allowed_clients.?=.+$', u'line': u'listen.allowed_clients = 127.0.0.1'})
ok: [web1] => (item={u'regexp': u'^pm\\.max_children.?=.+$', u'line': u'pm.max_children = 50'})
ok: [web1] => (item={u'regexp': u'^pm\\.start_servers.?=.+$', u'line': u'pm.start_servers = 5'})
ok: [web1] => (item={u'regexp': u'^pm\\.min_spare_servers.?=.+$', u'line': u'pm.min_spare_servers = 5'})
changed: [web1] => (item={u'regexp': u'^pm\\.max_spare_servers.?=.+$', u'line': u'pm.max_spare_servers = 5'})

TASK [geerlingguy.php : Ensure php-fpm is started and enabled at boot (if configured).] ********************************************************************************************
changed: [web1]

TASK [geerlingguy.git : Ensure git is installed (RedHat).] *************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.git : Update apt cache (Debian).] ********************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.git : Ensure git is installed (Debian).] *************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.git : Include OS-specific variables (RedHat).] *******************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.git : Include OS-specific variables (Fedora).] *******************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.git : Include OS-specific variables (Debian).] *******************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.git : Define git_install_from_source_dependencies.] **************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.git : Ensure git's dependencies are installed.] ******************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.git : Get installed version.] ************************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.git : Force git install if the version numbers do not match.] ****************************************************************************************************
skipping: [web1]

TASK [geerlingguy.git : Download git.] *********************************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.git : Expand git archive.] ***************************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.git : Build git.] ************************************************************************************************************************************************
skipping: [web1] => (item=all)
skipping: [web1] => (item=install)

TASK [Install package dependencies for Composer] ***********************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.composer : Set php_executable variable to a default if not defined.] *********************************************************************************************
skipping: [web1]

TASK [geerlingguy.composer : Check if Composer is installed.] **********************************************************************************************************************
ok: [web1]

TASK [geerlingguy.composer : Get Composer installer signature.] ********************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.composer : Download Composer installer.] *************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.composer : Run Composer installer.] ******************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.composer : Move Composer into globally-accessible location.] *****************************************************************************************************
skipping: [web1]

TASK [geerlingguy.composer : Update Composer to latest version (if configured).] ***************************************************************************************************
skipping: [web1]

TASK [geerlingguy.composer : Ensure composer directory exists.] ********************************************************************************************************************
ok: [web1]

TASK [geerlingguy.composer : Add GitHub OAuth token for Composer (if configured).] *************************************************************************************************
skipping: [web1]

TASK [geerlingguy.composer : include_tasks] ****************************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.composer : include_tasks] ****************************************************************************************************************************************
skipping: [web1]

TASK [Add a user to own developer portal site files] *******************************************************************************************************************************
ok: [web1]

TASK [Create drupal deploy dir to avoid permission issues.] ************************************************************************************************************************
changed: [web1]

TASK [geerlingguy.drupal : Add backwards-compatibility shims.] *********************************************************************************************************************
included: /apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.drupal/tasks/backwards-compatibility.yml for web1

TASK [geerlingguy.drupal : build_makefile shim] ************************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.drupal : build_composer shim] ************************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.drupal : build_composer_project shim] ****************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.drupal : install_site shim] **************************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.drupal : drupalvm_database shim] *********************************************************************************************************************************
skipping: [web1]

TASK [geerlingguy.drupal : Check if Drupal is already set up.] *********************************************************************************************************************
ok: [web1]

TASK [geerlingguy.drupal : Define drush_path if it's not already defined.] *********************************************************************************************************
skipping: [web1]

TASK [geerlingguy.drupal : Define drupal_site_exists.] *****************************************************************************************************************************
ok: [web1]

TASK [geerlingguy.drupal : include_tasks] ******************************************************************************************************************************************
included: /apps/drupal_test/devportal-kickstart-drupal-ansible-installer-master/roles/geerlingguy.drupal/tasks/deploy.yml for web1

TASK [geerlingguy.drupal : Ensure drupal_deploy_dir directory exists.] *************************************************************************************************************
changed: [web1]

TASK [geerlingguy.drupal : Check out Drupal to the docroot.] ***********************************************************************************************************************
ok: [web1]

TASK [geerlingguy.drupal : Check if a composer.json file is present.] **************************************************************************************************************
ok: [web1]

TASK [geerlingguy.drupal : Run composer install if composer.json is present.] ******************************************************************************************************
fatal: [web1]: FAILED! => {"changed": false, "msg": "Failed loading opcache.so: opcache.so: cannot open shared object file: No such file or directory Loading composer repositories with package information Updating dependencies Your requirements could not be resolved to an installable set of packages. Problem 1 - This package requires php ^7.2 but your PHP version (5.4.16) does not satisfy that requirement. Problem 2 - drupal/apigee_m10n 1.6.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement. - drupal/apigee_m10n 1.5.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement. - drupal/apigee_m10n 1.4.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement. - drupal/apigee_m10n 1.3.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement. - drupal/apigee_m10n 1.2.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement. - drupal/apigee_m10n 1.1.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement. - drupal/apigee_m10n 1.0.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement. - drupal/apigee_m10n 1.0.0-rc2 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement. - drupal/apigee_m10n 1.0.0-rc1 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement. - drupal/apigee_m10n 1.0.0-beta3 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement. - drupal/apigee_m10n 1.0.0-beta1 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement. - drupal/apigee_m10n 1.0.0-alpha3 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement. - drupal/apigee_m10n 1.0.0-alpha2 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement. - drupal/apigee_m10n 1.0.0-alpha1 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement. - drupal/apigee_m10n 1.x-dev requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement. - Installation request for drupal/apigee_m10n ^1.0.0 -> satisfiable by drupal/apigee_m10n[1.x-dev, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-alpha3, 1.0.0-beta1, 1.0.0-beta3, 1.0.0-rc1, 1.0.0-rc2, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0]. Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.", "stdout": "Failed loading opcache.so:  opcache.so: cannot open shared object file: No such file or directory\nLoading composer repositories with package information\nUpdating dependencies\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - This package requires php ^7.2 but your PHP version (5.4.16) does not satisfy that requirement.\n  Problem 2\n    - drupal/apigee_m10n 1.6.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - drupal/apigee_m10n 1.5.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - drupal/apigee_m10n 1.4.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - drupal/apigee_m10n 1.3.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - drupal/apigee_m10n 1.2.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - drupal/apigee_m10n 1.1.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - drupal/apigee_m10n 1.0.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - drupal/apigee_m10n 1.0.0-rc2 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - drupal/apigee_m10n 1.0.0-rc1 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - drupal/apigee_m10n 1.0.0-beta3 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - drupal/apigee_m10n 1.0.0-beta1 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - drupal/apigee_m10n 1.0.0-alpha3 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - drupal/apigee_m10n 1.0.0-alpha2 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - drupal/apigee_m10n 1.0.0-alpha1 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - drupal/apigee_m10n 1.x-dev requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.\n    - Installation request for drupal/apigee_m10n ^1.0.0 -> satisfiable by drupal/apigee_m10n[1.x-dev, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-alpha3, 1.0.0-beta1, 1.0.0-beta3, 1.0.0-rc1, 1.0.0-rc2, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0].\n\nRunning update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.\n", "stdout_lines": ["Failed loading opcache.so:  opcache.so: cannot open shared object file: No such file or directory", "Loading composer repositories with package information", "Updating dependencies", "Your requirements could not be resolved to an installable set of packages.", "", "  Problem 1", "    - This package requires php ^7.2 but your PHP version (5.4.16) does not satisfy that requirement.", "  Problem 2", "    - drupal/apigee_m10n 1.6.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - drupal/apigee_m10n 1.5.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - drupal/apigee_m10n 1.4.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - drupal/apigee_m10n 1.3.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - drupal/apigee_m10n 1.2.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - drupal/apigee_m10n 1.1.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - drupal/apigee_m10n 1.0.0 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - drupal/apigee_m10n 1.0.0-rc2 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - drupal/apigee_m10n 1.0.0-rc1 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - drupal/apigee_m10n 1.0.0-beta3 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - drupal/apigee_m10n 1.0.0-beta1 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - drupal/apigee_m10n 1.0.0-alpha3 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - drupal/apigee_m10n 1.0.0-alpha2 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - drupal/apigee_m10n 1.0.0-alpha1 requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - drupal/apigee_m10n 1.x-dev requires php >=7.1 -> your PHP version (5.4.16) does not satisfy that requirement.", "    - Installation request for drupal/apigee_m10n ^1.0.0 -> satisfiable by drupal/apigee_m10n[1.x-dev, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-alpha3, 1.0.0-beta1, 1.0.0-beta3, 1.0.0-rc1, 1.0.0-rc2, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0].", "", "Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems."]}

RUNNING HANDLER [geerlingguy.php : restart webserver] ******************************************************************************************************************************

RUNNING HANDLER [geerlingguy.php : restart php-fpm] ********************************************************************************************************************************

PLAY RECAP *************************************************************************************************************************************************************************
db1                        : ok=30   changed=0    unreachable=0    failed=0    skipped=20   rescued=0    ignored=0
web1                       : ok=49   changed=7    unreachable=0    failed=1    skipped=45   rescued=0    ignored=0

**Comment by giteshk** [comment]
Can you go through the Remi configuration and apply the right package? 
https://rpms.remirepo.net/wizard/

Or you may try changes in this PR to see if it helps  https://github.com/apigee/devportal-kickstart-drupal-ansible-installer/pull/7

**Comment by jackd12** [comment]
TY .. upgraded via remi and that worked.
